/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VoucherRouteImport } from './routes/voucher'
import { Route as RelatedPartyRouteImport } from './routes/related-party'
import { Route as ProfitabilityRouteImport } from './routes/profitability'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MgmtRouteImport } from './routes/mgmt'
import { Route as LedgerRouteImport } from './routes/ledger'
import { Route as HomeRouteImport } from './routes/home'
import { Route as EntryRouteImport } from './routes/entry'
import { Route as CreditorsRouteImport } from './routes/creditors'
import { Route as CashRouteImport } from './routes/cash'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfitabilityStoreRouteImport } from './routes/profitability_.store'
import { Route as OperationsSalesRouteImport } from './routes/operations.sales'
import { Route as MgmtStoresRouteImport } from './routes/mgmt_.stores'
import { Route as MgmtStoreExpensesRouteImport } from './routes/mgmt_.store-expenses'
import { Route as MgmtReconciliationRouteImport } from './routes/mgmt_.reconciliation'
import { Route as MgmtMappingRouteImport } from './routes/mgmt_.mapping'
import { Route as MgmtDcExpensesRouteImport } from './routes/mgmt_.dc-expenses'
import { Route as EntryTillRouteImport } from './routes/entry_.till'
import { Route as EntryListRouteImport } from './routes/entry_.list'
import { Route as CreditorsVendorRouteImport } from './routes/creditors_.vendor'
import { Route as ControlUsersRouteImport } from './routes/control.users'
import { Route as ControlInboxRouteImport } from './routes/control.inbox'
import { Route as ControlCorrectionsRouteImport } from './routes/control.corrections'
import { Route as ControlCloseRouteImport } from './routes/control.close'
import { Route as ControlAdjustmentsRouteImport } from './routes/control.adjustments'

const VoucherRoute = VoucherRouteImport.update({
  id: '/voucher',
  path: '/voucher',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatedPartyRoute = RelatedPartyRouteImport.update({
  id: '/related-party',
  path: '/related-party',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfitabilityRoute = ProfitabilityRouteImport.update({
  id: '/profitability',
  path: '/profitability',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MgmtRoute = MgmtRouteImport.update({
  id: '/mgmt',
  path: '/mgmt',
  getParentRoute: () => rootRouteImport,
} as any)
const LedgerRoute = LedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const EntryRoute = EntryRouteImport.update({
  id: '/entry',
  path: '/entry',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditorsRoute = CreditorsRouteImport.update({
  id: '/creditors',
  path: '/creditors',
  getParentRoute: () => rootRouteImport,
} as any)
const CashRoute = CashRouteImport.update({
  id: '/cash',
  path: '/cash',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfitabilityStoreRoute = ProfitabilityStoreRouteImport.update({
  id: '/profitability_/store',
  path: '/profitability/store',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsSalesRoute = OperationsSalesRouteImport.update({
  id: '/operations/sales',
  path: '/operations/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const MgmtStoresRoute = MgmtStoresRouteImport.update({
  id: '/mgmt_/stores',
  path: '/mgmt/stores',
  getParentRoute: () => rootRouteImport,
} as any)
const MgmtStoreExpensesRoute = MgmtStoreExpensesRouteImport.update({
  id: '/mgmt_/store-expenses',
  path: '/mgmt/store-expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const MgmtReconciliationRoute = MgmtReconciliationRouteImport.update({
  id: '/mgmt_/reconciliation',
  path: '/mgmt/reconciliation',
  getParentRoute: () => rootRouteImport,
} as any)
const MgmtMappingRoute = MgmtMappingRouteImport.update({
  id: '/mgmt_/mapping',
  path: '/mgmt/mapping',
  getParentRoute: () => rootRouteImport,
} as any)
const MgmtDcExpensesRoute = MgmtDcExpensesRouteImport.update({
  id: '/mgmt_/dc-expenses',
  path: '/mgmt/dc-expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const EntryTillRoute = EntryTillRouteImport.update({
  id: '/entry_/till',
  path: '/entry/till',
  getParentRoute: () => rootRouteImport,
} as any)
const EntryListRoute = EntryListRouteImport.update({
  id: '/entry_/list',
  path: '/entry/list',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditorsVendorRoute = CreditorsVendorRouteImport.update({
  id: '/creditors_/vendor',
  path: '/creditors/vendor',
  getParentRoute: () => rootRouteImport,
} as any)
const ControlUsersRoute = ControlUsersRouteImport.update({
  id: '/control/users',
  path: '/control/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ControlInboxRoute = ControlInboxRouteImport.update({
  id: '/control/inbox',
  path: '/control/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const ControlCorrectionsRoute = ControlCorrectionsRouteImport.update({
  id: '/control/corrections',
  path: '/control/corrections',
  getParentRoute: () => rootRouteImport,
} as any)
const ControlCloseRoute = ControlCloseRouteImport.update({
  id: '/control/close',
  path: '/control/close',
  getParentRoute: () => rootRouteImport,
} as any)
const ControlAdjustmentsRoute = ControlAdjustmentsRouteImport.update({
  id: '/control/adjustments',
  path: '/control/adjustments',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cash': typeof CashRoute
  '/creditors': typeof CreditorsRoute
  '/entry': typeof EntryRoute
  '/home': typeof HomeRoute
  '/ledger': typeof LedgerRoute
  '/mgmt': typeof MgmtRoute
  '/profile': typeof ProfileRoute
  '/profitability': typeof ProfitabilityRoute
  '/related-party': typeof RelatedPartyRoute
  '/voucher': typeof VoucherRoute
  '/control/adjustments': typeof ControlAdjustmentsRoute
  '/control/close': typeof ControlCloseRoute
  '/control/corrections': typeof ControlCorrectionsRoute
  '/control/inbox': typeof ControlInboxRoute
  '/control/users': typeof ControlUsersRoute
  '/creditors/vendor': typeof CreditorsVendorRoute
  '/entry/list': typeof EntryListRoute
  '/entry/till': typeof EntryTillRoute
  '/mgmt/dc-expenses': typeof MgmtDcExpensesRoute
  '/mgmt/mapping': typeof MgmtMappingRoute
  '/mgmt/reconciliation': typeof MgmtReconciliationRoute
  '/mgmt/store-expenses': typeof MgmtStoreExpensesRoute
  '/mgmt/stores': typeof MgmtStoresRoute
  '/operations/sales': typeof OperationsSalesRoute
  '/profitability/store': typeof ProfitabilityStoreRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cash': typeof CashRoute
  '/creditors': typeof CreditorsRoute
  '/entry': typeof EntryRoute
  '/home': typeof HomeRoute
  '/ledger': typeof LedgerRoute
  '/mgmt': typeof MgmtRoute
  '/profile': typeof ProfileRoute
  '/profitability': typeof ProfitabilityRoute
  '/related-party': typeof RelatedPartyRoute
  '/voucher': typeof VoucherRoute
  '/control/adjustments': typeof ControlAdjustmentsRoute
  '/control/close': typeof ControlCloseRoute
  '/control/corrections': typeof ControlCorrectionsRoute
  '/control/inbox': typeof ControlInboxRoute
  '/control/users': typeof ControlUsersRoute
  '/creditors/vendor': typeof CreditorsVendorRoute
  '/entry/list': typeof EntryListRoute
  '/entry/till': typeof EntryTillRoute
  '/mgmt/dc-expenses': typeof MgmtDcExpensesRoute
  '/mgmt/mapping': typeof MgmtMappingRoute
  '/mgmt/reconciliation': typeof MgmtReconciliationRoute
  '/mgmt/store-expenses': typeof MgmtStoreExpensesRoute
  '/mgmt/stores': typeof MgmtStoresRoute
  '/operations/sales': typeof OperationsSalesRoute
  '/profitability/store': typeof ProfitabilityStoreRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cash': typeof CashRoute
  '/creditors': typeof CreditorsRoute
  '/entry': typeof EntryRoute
  '/home': typeof HomeRoute
  '/ledger': typeof LedgerRoute
  '/mgmt': typeof MgmtRoute
  '/profile': typeof ProfileRoute
  '/profitability': typeof ProfitabilityRoute
  '/related-party': typeof RelatedPartyRoute
  '/voucher': typeof VoucherRoute
  '/control/adjustments': typeof ControlAdjustmentsRoute
  '/control/close': typeof ControlCloseRoute
  '/control/corrections': typeof ControlCorrectionsRoute
  '/control/inbox': typeof ControlInboxRoute
  '/control/users': typeof ControlUsersRoute
  '/creditors_/vendor': typeof CreditorsVendorRoute
  '/entry_/list': typeof EntryListRoute
  '/entry_/till': typeof EntryTillRoute
  '/mgmt_/dc-expenses': typeof MgmtDcExpensesRoute
  '/mgmt_/mapping': typeof MgmtMappingRoute
  '/mgmt_/reconciliation': typeof MgmtReconciliationRoute
  '/mgmt_/store-expenses': typeof MgmtStoreExpensesRoute
  '/mgmt_/stores': typeof MgmtStoresRoute
  '/operations/sales': typeof OperationsSalesRoute
  '/profitability_/store': typeof ProfitabilityStoreRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cash'
    | '/creditors'
    | '/entry'
    | '/home'
    | '/ledger'
    | '/mgmt'
    | '/profile'
    | '/profitability'
    | '/related-party'
    | '/voucher'
    | '/control/adjustments'
    | '/control/close'
    | '/control/corrections'
    | '/control/inbox'
    | '/control/users'
    | '/creditors/vendor'
    | '/entry/list'
    | '/entry/till'
    | '/mgmt/dc-expenses'
    | '/mgmt/mapping'
    | '/mgmt/reconciliation'
    | '/mgmt/store-expenses'
    | '/mgmt/stores'
    | '/operations/sales'
    | '/profitability/store'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cash'
    | '/creditors'
    | '/entry'
    | '/home'
    | '/ledger'
    | '/mgmt'
    | '/profile'
    | '/profitability'
    | '/related-party'
    | '/voucher'
    | '/control/adjustments'
    | '/control/close'
    | '/control/corrections'
    | '/control/inbox'
    | '/control/users'
    | '/creditors/vendor'
    | '/entry/list'
    | '/entry/till'
    | '/mgmt/dc-expenses'
    | '/mgmt/mapping'
    | '/mgmt/reconciliation'
    | '/mgmt/store-expenses'
    | '/mgmt/stores'
    | '/operations/sales'
    | '/profitability/store'
  id:
    | '__root__'
    | '/'
    | '/cash'
    | '/creditors'
    | '/entry'
    | '/home'
    | '/ledger'
    | '/mgmt'
    | '/profile'
    | '/profitability'
    | '/related-party'
    | '/voucher'
    | '/control/adjustments'
    | '/control/close'
    | '/control/corrections'
    | '/control/inbox'
    | '/control/users'
    | '/creditors_/vendor'
    | '/entry_/list'
    | '/entry_/till'
    | '/mgmt_/dc-expenses'
    | '/mgmt_/mapping'
    | '/mgmt_/reconciliation'
    | '/mgmt_/store-expenses'
    | '/mgmt_/stores'
    | '/operations/sales'
    | '/profitability_/store'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CashRoute: typeof CashRoute
  CreditorsRoute: typeof CreditorsRoute
  EntryRoute: typeof EntryRoute
  HomeRoute: typeof HomeRoute
  LedgerRoute: typeof LedgerRoute
  MgmtRoute: typeof MgmtRoute
  ProfileRoute: typeof ProfileRoute
  ProfitabilityRoute: typeof ProfitabilityRoute
  RelatedPartyRoute: typeof RelatedPartyRoute
  VoucherRoute: typeof VoucherRoute
  ControlAdjustmentsRoute: typeof ControlAdjustmentsRoute
  ControlCloseRoute: typeof ControlCloseRoute
  ControlCorrectionsRoute: typeof ControlCorrectionsRoute
  ControlInboxRoute: typeof ControlInboxRoute
  ControlUsersRoute: typeof ControlUsersRoute
  CreditorsVendorRoute: typeof CreditorsVendorRoute
  EntryListRoute: typeof EntryListRoute
  EntryTillRoute: typeof EntryTillRoute
  MgmtDcExpensesRoute: typeof MgmtDcExpensesRoute
  MgmtMappingRoute: typeof MgmtMappingRoute
  MgmtReconciliationRoute: typeof MgmtReconciliationRoute
  MgmtStoreExpensesRoute: typeof MgmtStoreExpensesRoute
  MgmtStoresRoute: typeof MgmtStoresRoute
  OperationsSalesRoute: typeof OperationsSalesRoute
  ProfitabilityStoreRoute: typeof ProfitabilityStoreRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/voucher': {
      id: '/voucher'
      path: '/voucher'
      fullPath: '/voucher'
      preLoaderRoute: typeof VoucherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/related-party': {
      id: '/related-party'
      path: '/related-party'
      fullPath: '/related-party'
      preLoaderRoute: typeof RelatedPartyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profitability': {
      id: '/profitability'
      path: '/profitability'
      fullPath: '/profitability'
      preLoaderRoute: typeof ProfitabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mgmt': {
      id: '/mgmt'
      path: '/mgmt'
      fullPath: '/mgmt'
      preLoaderRoute: typeof MgmtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ledger': {
      id: '/ledger'
      path: '/ledger'
      fullPath: '/ledger'
      preLoaderRoute: typeof LedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entry': {
      id: '/entry'
      path: '/entry'
      fullPath: '/entry'
      preLoaderRoute: typeof EntryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creditors': {
      id: '/creditors'
      path: '/creditors'
      fullPath: '/creditors'
      preLoaderRoute: typeof CreditorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cash': {
      id: '/cash'
      path: '/cash'
      fullPath: '/cash'
      preLoaderRoute: typeof CashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profitability_/store': {
      id: '/profitability_/store'
      path: '/profitability/store'
      fullPath: '/profitability/store'
      preLoaderRoute: typeof ProfitabilityStoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations/sales': {
      id: '/operations/sales'
      path: '/operations/sales'
      fullPath: '/operations/sales'
      preLoaderRoute: typeof OperationsSalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mgmt_/stores': {
      id: '/mgmt_/stores'
      path: '/mgmt/stores'
      fullPath: '/mgmt/stores'
      preLoaderRoute: typeof MgmtStoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mgmt_/store-expenses': {
      id: '/mgmt_/store-expenses'
      path: '/mgmt/store-expenses'
      fullPath: '/mgmt/store-expenses'
      preLoaderRoute: typeof MgmtStoreExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mgmt_/reconciliation': {
      id: '/mgmt_/reconciliation'
      path: '/mgmt/reconciliation'
      fullPath: '/mgmt/reconciliation'
      preLoaderRoute: typeof MgmtReconciliationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mgmt_/mapping': {
      id: '/mgmt_/mapping'
      path: '/mgmt/mapping'
      fullPath: '/mgmt/mapping'
      preLoaderRoute: typeof MgmtMappingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mgmt_/dc-expenses': {
      id: '/mgmt_/dc-expenses'
      path: '/mgmt/dc-expenses'
      fullPath: '/mgmt/dc-expenses'
      preLoaderRoute: typeof MgmtDcExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entry_/till': {
      id: '/entry_/till'
      path: '/entry/till'
      fullPath: '/entry/till'
      preLoaderRoute: typeof EntryTillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entry_/list': {
      id: '/entry_/list'
      path: '/entry/list'
      fullPath: '/entry/list'
      preLoaderRoute: typeof EntryListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creditors_/vendor': {
      id: '/creditors_/vendor'
      path: '/creditors/vendor'
      fullPath: '/creditors/vendor'
      preLoaderRoute: typeof CreditorsVendorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/control/users': {
      id: '/control/users'
      path: '/control/users'
      fullPath: '/control/users'
      preLoaderRoute: typeof ControlUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/control/inbox': {
      id: '/control/inbox'
      path: '/control/inbox'
      fullPath: '/control/inbox'
      preLoaderRoute: typeof ControlInboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/control/corrections': {
      id: '/control/corrections'
      path: '/control/corrections'
      fullPath: '/control/corrections'
      preLoaderRoute: typeof ControlCorrectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/control/close': {
      id: '/control/close'
      path: '/control/close'
      fullPath: '/control/close'
      preLoaderRoute: typeof ControlCloseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/control/adjustments': {
      id: '/control/adjustments'
      path: '/control/adjustments'
      fullPath: '/control/adjustments'
      preLoaderRoute: typeof ControlAdjustmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CashRoute: CashRoute,
  CreditorsRoute: CreditorsRoute,
  EntryRoute: EntryRoute,
  HomeRoute: HomeRoute,
  LedgerRoute: LedgerRoute,
  MgmtRoute: MgmtRoute,
  ProfileRoute: ProfileRoute,
  ProfitabilityRoute: ProfitabilityRoute,
  RelatedPartyRoute: RelatedPartyRoute,
  VoucherRoute: VoucherRoute,
  ControlAdjustmentsRoute: ControlAdjustmentsRoute,
  ControlCloseRoute: ControlCloseRoute,
  ControlCorrectionsRoute: ControlCorrectionsRoute,
  ControlInboxRoute: ControlInboxRoute,
  ControlUsersRoute: ControlUsersRoute,
  CreditorsVendorRoute: CreditorsVendorRoute,
  EntryListRoute: EntryListRoute,
  EntryTillRoute: EntryTillRoute,
  MgmtDcExpensesRoute: MgmtDcExpensesRoute,
  MgmtMappingRoute: MgmtMappingRoute,
  MgmtReconciliationRoute: MgmtReconciliationRoute,
  MgmtStoreExpensesRoute: MgmtStoreExpensesRoute,
  MgmtStoresRoute: MgmtStoresRoute,
  OperationsSalesRoute: OperationsSalesRoute,
  ProfitabilityStoreRoute: ProfitabilityStoreRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
