/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VoucherRouteImport } from './routes/voucher'
import { Route as ProfitabilityRouteImport } from './routes/profitability'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LedgerRouteImport } from './routes/ledger'
import { Route as HomeRouteImport } from './routes/home'
import { Route as EntryRouteImport } from './routes/entry'
import { Route as CreditorsRouteImport } from './routes/creditors'
import { Route as CashRouteImport } from './routes/cash'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfitabilityStoreRouteImport } from './routes/profitability_.store'
import { Route as OperationsSalesRouteImport } from './routes/operations.sales'
import { Route as EntryTillRouteImport } from './routes/entry_.till'
import { Route as EntryListRouteImport } from './routes/entry_.list'
import { Route as CreditorsVendorRouteImport } from './routes/creditors_.vendor'

const VoucherRoute = VoucherRouteImport.update({
  id: '/voucher',
  path: '/voucher',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfitabilityRoute = ProfitabilityRouteImport.update({
  id: '/profitability',
  path: '/profitability',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LedgerRoute = LedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const EntryRoute = EntryRouteImport.update({
  id: '/entry',
  path: '/entry',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditorsRoute = CreditorsRouteImport.update({
  id: '/creditors',
  path: '/creditors',
  getParentRoute: () => rootRouteImport,
} as any)
const CashRoute = CashRouteImport.update({
  id: '/cash',
  path: '/cash',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfitabilityStoreRoute = ProfitabilityStoreRouteImport.update({
  id: '/profitability_/store',
  path: '/profitability/store',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsSalesRoute = OperationsSalesRouteImport.update({
  id: '/operations/sales',
  path: '/operations/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const EntryTillRoute = EntryTillRouteImport.update({
  id: '/entry_/till',
  path: '/entry/till',
  getParentRoute: () => rootRouteImport,
} as any)
const EntryListRoute = EntryListRouteImport.update({
  id: '/entry_/list',
  path: '/entry/list',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditorsVendorRoute = CreditorsVendorRouteImport.update({
  id: '/creditors_/vendor',
  path: '/creditors/vendor',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cash': typeof CashRoute
  '/creditors': typeof CreditorsRoute
  '/entry': typeof EntryRoute
  '/home': typeof HomeRoute
  '/ledger': typeof LedgerRoute
  '/profile': typeof ProfileRoute
  '/profitability': typeof ProfitabilityRoute
  '/voucher': typeof VoucherRoute
  '/creditors/vendor': typeof CreditorsVendorRoute
  '/entry/list': typeof EntryListRoute
  '/entry/till': typeof EntryTillRoute
  '/operations/sales': typeof OperationsSalesRoute
  '/profitability/store': typeof ProfitabilityStoreRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cash': typeof CashRoute
  '/creditors': typeof CreditorsRoute
  '/entry': typeof EntryRoute
  '/home': typeof HomeRoute
  '/ledger': typeof LedgerRoute
  '/profile': typeof ProfileRoute
  '/profitability': typeof ProfitabilityRoute
  '/voucher': typeof VoucherRoute
  '/creditors/vendor': typeof CreditorsVendorRoute
  '/entry/list': typeof EntryListRoute
  '/entry/till': typeof EntryTillRoute
  '/operations/sales': typeof OperationsSalesRoute
  '/profitability/store': typeof ProfitabilityStoreRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cash': typeof CashRoute
  '/creditors': typeof CreditorsRoute
  '/entry': typeof EntryRoute
  '/home': typeof HomeRoute
  '/ledger': typeof LedgerRoute
  '/profile': typeof ProfileRoute
  '/profitability': typeof ProfitabilityRoute
  '/voucher': typeof VoucherRoute
  '/creditors_/vendor': typeof CreditorsVendorRoute
  '/entry_/list': typeof EntryListRoute
  '/entry_/till': typeof EntryTillRoute
  '/operations/sales': typeof OperationsSalesRoute
  '/profitability_/store': typeof ProfitabilityStoreRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cash'
    | '/creditors'
    | '/entry'
    | '/home'
    | '/ledger'
    | '/profile'
    | '/profitability'
    | '/voucher'
    | '/creditors/vendor'
    | '/entry/list'
    | '/entry/till'
    | '/operations/sales'
    | '/profitability/store'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cash'
    | '/creditors'
    | '/entry'
    | '/home'
    | '/ledger'
    | '/profile'
    | '/profitability'
    | '/voucher'
    | '/creditors/vendor'
    | '/entry/list'
    | '/entry/till'
    | '/operations/sales'
    | '/profitability/store'
  id:
    | '__root__'
    | '/'
    | '/cash'
    | '/creditors'
    | '/entry'
    | '/home'
    | '/ledger'
    | '/profile'
    | '/profitability'
    | '/voucher'
    | '/creditors_/vendor'
    | '/entry_/list'
    | '/entry_/till'
    | '/operations/sales'
    | '/profitability_/store'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CashRoute: typeof CashRoute
  CreditorsRoute: typeof CreditorsRoute
  EntryRoute: typeof EntryRoute
  HomeRoute: typeof HomeRoute
  LedgerRoute: typeof LedgerRoute
  ProfileRoute: typeof ProfileRoute
  ProfitabilityRoute: typeof ProfitabilityRoute
  VoucherRoute: typeof VoucherRoute
  CreditorsVendorRoute: typeof CreditorsVendorRoute
  EntryListRoute: typeof EntryListRoute
  EntryTillRoute: typeof EntryTillRoute
  OperationsSalesRoute: typeof OperationsSalesRoute
  ProfitabilityStoreRoute: typeof ProfitabilityStoreRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/voucher': {
      id: '/voucher'
      path: '/voucher'
      fullPath: '/voucher'
      preLoaderRoute: typeof VoucherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profitability': {
      id: '/profitability'
      path: '/profitability'
      fullPath: '/profitability'
      preLoaderRoute: typeof ProfitabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ledger': {
      id: '/ledger'
      path: '/ledger'
      fullPath: '/ledger'
      preLoaderRoute: typeof LedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entry': {
      id: '/entry'
      path: '/entry'
      fullPath: '/entry'
      preLoaderRoute: typeof EntryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creditors': {
      id: '/creditors'
      path: '/creditors'
      fullPath: '/creditors'
      preLoaderRoute: typeof CreditorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cash': {
      id: '/cash'
      path: '/cash'
      fullPath: '/cash'
      preLoaderRoute: typeof CashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profitability_/store': {
      id: '/profitability_/store'
      path: '/profitability/store'
      fullPath: '/profitability/store'
      preLoaderRoute: typeof ProfitabilityStoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations/sales': {
      id: '/operations/sales'
      path: '/operations/sales'
      fullPath: '/operations/sales'
      preLoaderRoute: typeof OperationsSalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entry_/till': {
      id: '/entry_/till'
      path: '/entry/till'
      fullPath: '/entry/till'
      preLoaderRoute: typeof EntryTillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entry_/list': {
      id: '/entry_/list'
      path: '/entry/list'
      fullPath: '/entry/list'
      preLoaderRoute: typeof EntryListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creditors_/vendor': {
      id: '/creditors_/vendor'
      path: '/creditors/vendor'
      fullPath: '/creditors/vendor'
      preLoaderRoute: typeof CreditorsVendorRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CashRoute: CashRoute,
  CreditorsRoute: CreditorsRoute,
  EntryRoute: EntryRoute,
  HomeRoute: HomeRoute,
  LedgerRoute: LedgerRoute,
  ProfileRoute: ProfileRoute,
  ProfitabilityRoute: ProfitabilityRoute,
  VoucherRoute: VoucherRoute,
  CreditorsVendorRoute: CreditorsVendorRoute,
  EntryListRoute: EntryListRoute,
  EntryTillRoute: EntryTillRoute,
  OperationsSalesRoute: OperationsSalesRoute,
  ProfitabilityStoreRoute: ProfitabilityStoreRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
